/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b913a822-5ac4-4ace-8448-e38b9dba4e6b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8aPYRihn3",
    "aws_user_pools_web_client_id": "6cs2peo8fktfvtaqul7gqb3s45",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://vx37nit47zb5plnvqny6hhpu4m.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-535mhgrhpjhotpejdkh2voxgfq",
    "aws_user_files_s3_bucket": "navkamal201927-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
